# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0006_workflowtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelJoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channelId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.Channel')),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('assignToUser', models.TextField(max_length=50)),
                ('form', models.TextField(max_length=400)),
                ('taskName', models.TextField(max_length=100)),
                ('State', models.BooleanField(default=True)),
                ('listenner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
