# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0008_auto_20170513_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='executingflow',
            name='currentFlow',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='executingflow',
            name='executingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='executingflow',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executingflow',
            name='templateId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='workflows.WorkflowTemplate'),
        ),
    ]
