# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0009_auto_20170518_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtask',
            name='State',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='listenner',
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='belongToWFId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.ExecutingFlow'),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='currentFlow',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='listener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listener', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executingflow',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingtask',
            name='assignToUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
