# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_auto_20170522_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='executingflow',
            name='xml',
            field=models.TextField(default=''),
        ),
    ]
