# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0012_executingflow_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtask',
            name='assignToUser',
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='assignToUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
